spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path=/service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
