server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native  

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config-repo/shared
            - classpath:/config-repo/complain-service
            - classpath:/config-repo/api-gateway
            - classpath:/config-repo/eureka-server
            - classpath:/config-repo/auth-service
            - classpath:/config-repo/orchestration-service
            - classpath:/config-repo/global-service
